title: Kang Ji Min
description: > # this means to ignore newlines until "baseurl:"
  하이요
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Kang9215892854.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: 강지민
tagline: 학생
about-description: 학생 # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: jimink2018@gmail.com  # Add your Email address
phone: 010 4722 9430 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: Kang9215892854 # Add your Github handle
twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
