title: Seo Min Seong
description: > # this means to ignore newlines until "baseurl:"
  하이요
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Kang9215892854.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'  
blog_theme: dark # Or use dark

# Profile information
name: 서민성
tagline: 서민성
about-description: 백수 # Add Discription
pic: minseong.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: dfhwasgfbqwo@gmail.com  # Add your Email address
phone: 010 1234 5678 # Add your Phone number
website: www.youtube.com/?app=desktop&hl=ko&gl=KR # Add your website, do not add http://
github: sms6874 # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.mdd

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
